FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /app
#add the work directory.
#And this sets the directory that the container starts in.
#And the main purpose of this is that any future commands that we execute inside this file happen inside
#this working directory.


# copy csproj and restore as distinct layers
COPY *.csproj ./
#copy .csproj into working directory
RUN dotnet restore
#And then inside our working directory, we're going to run dotnet restore  against that csproj  file, 

#and that restores all of our dependencies that are listed inside there.


# copy everything else and build
COPY . ./

#that's going to take all of our content inside our projects and copy that into our working 
#directory.      


RUN dotnet publish -c Release -o out
#And we're going to create a configuration that's called release.
#And then we specify the directory we want to put this out into.

# build runtime image
#We can use a smaller version and we can just use the runtime instead at this point.

#So we need the SDK to run the 'net restore' command and a 'dotnet publish' commands.

#But once we've done that, we can then go and use a smaller image that just contains the runtime 
#instead of the full SDK.

FROM mcr.microsoft.com/dotnet/aspnet:7.0

#And then because we're using the new image, we need to specify the work directory again 
#and keep it as  /app.
WORKDIR /app

# And then we're going to copy everything that's contained in our build environment that 
# we were using up here. And we specified that stash --from=build-env. And then we're going 
# to say that we're going to copy that from the /app/out into . , which is the root of 
# our container. 

# So everything that's inside that "out" directory that we created here is going to be copied 
# to the root of our container.

COPY --from=build-env /app/out .
ENTRYPOINT [ "dotnet","API.dll" ]

#So if you decided to call your project something other than API at this point, 
#you would need to tell

#it what you called it. I called mine API.

#So that's what I'm putting inside here because that's what's going to be generated when 
#we publish our application, we're going to have an API DLL.

#And that's the entry point to our application. It looks inside the program class.
#It executes that code in there and then runs our application.
